<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLUMNxr6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLUMNxr6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLUMNxr6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLUMNxr6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLUMNxr6\App_KernelDevDebugContainer([
    'container.build_hash' => 'LUMNxr6',
    'container.build_id' => 'a5d8d03a',
    'container.build_time' => 1609280213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLUMNxr6');
