# https://help.github.com/en/actions
name: Full CI process for Symfony 5
on:
  push:
    branches:
      - master
env:
  ES_HTTP_PORT: 9209
jobs:
  symfony:
    name: Symfony 5.2 (PHP ${{ matrix.php-versions }})
    # https://hub.docker.com/_/ubuntu/
    runs-on: ubuntu-20.04
    services:
      # https://docs.docker.com/samples/library/mysql/
      database:
        image: 'postgres:alpine'
        env:
          POSTGRES_PASSWORD: main
          POSTGRES_USER: main
          POSTGRES_DB: main
        ports:
          - '49153:5432'
      # https://hub.docker.com/_/elasticsearch/
      php:
        image: php:7.4-fpm
        ports:
          - 9000:9000
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4', '8.0']
    steps:
      # —— Check Elasticsearch 🔎 ——————————————————————————————————————————————
      - name: Check the unit test
        run: |
          php bin/phpunit --configuration config.xml --testsuite unit-test
